# Homework 1
## Mengxiang Jiang

The majority of the code here comes from the [NumPy Cheat Sheet](https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python)
and the [Pandas Basics Cheat Sheet](https://www.datacamp.com/cheat-sheet/pandas-cheat-sheet-for-data-science-in-python). 
If the code comes from somewhere else it will have a source linked to the original. Some of the code has been modified from the original to show errors or to remove errors.

### Importing Numpy

In [1]:
import numpy as np

### Creating Arrays

In [2]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float)

print(f"a: {a}\n")
print(f"b: {b}\n")
print(f"c: {c}\n")

a: [1 2 3]

b: [[1.5 2.  3. ]
 [4.  5.  6. ]]

c: [[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]



In [3]:
print(f"zeros: {np.zeros((3,4))}") #Create an array of zeros
print(f"ones: {np.ones((2,3,4),dtype=np.int16)}") #Create an array of ones
print(f"arange: { np.arange(10,25,5)}") #Create an array of evenly spaced values (step value)
print(f"linspace: {np.linspace(0,2,9)}") #Create an array of evenlyspaced values (number of samples)
print(f"full: {np.full((2,2),7)}") #Create a constant array
print(f"eye: {np.eye(2)}") #Create a 2X2 identity matrix
print(f"random: {np.random.random((2,2))}") #Create an array with random values
print(f"empty: {np.empty((3,2))}") #Create an empty array

zeros: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones: [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
arange: [10 15 20]
linspace: [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
full: [[7 7]
 [7 7]]
eye: [[1. 0.]
 [0. 1.]]
random: [[0.28967617 0.28774202]
 [0.50286383 0.6963722 ]]
empty: [[1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]]


### I/O

In [4]:
a = np.random.random((2,2))
b = np.eye(2)
print(a)
print(b)
np.save('my_array' , a)
print(np.load('my_array.npy'))

[[0.171079   0.71808901]
 [0.41523274 0.87987844]]
[[1. 0.]
 [0. 1.]]
[[0.171079   0.71808901]
 [0.41523274 0.87987844]]


[numpy.savez](https://numpy.org/doc/stable/reference/generated/numpy.savez.html)

In [5]:
np.savez('array.npz', a=a, b=b)
npzfile = np.load('array.npz')
print(npzfile['a'])
print(npzfile['b'])

[[0.171079   0.71808901]
 [0.41523274 0.87987844]]
[[1. 0.]
 [0. 1.]]


[numpy.savetext](https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html)

In [6]:
np.savetxt('myfile.txt', a)
print(np.loadtxt('myfile.txt'))


[[0.171079   0.71808901]
 [0.41523274 0.87987844]]


In [7]:
np.savetxt( 'my_file.csv', a, delimiter=',')
print(np.genfromtxt('my_file.csv', delimiter=','))

[[0.171079   0.71808901]
 [0.41523274 0.87987844]]


### Asking For Help

In [8]:
print(np.info(np.ndarray.dtype))

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>
None
