# Homework 1
## Mengxiang Jiang

The majority of the code here comes from the [NumPy Cheat Sheet](https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python)
and the [Pandas Basics Cheat Sheet](https://www.datacamp.com/cheat-sheet/pandas-cheat-sheet-for-data-science-in-python). 
If the code comes from somewhere else it will have a source linked to the original. Some of the code has been modified from the original to show errors or to remove errors.

### Importing Numpy

In [1]:
import numpy as np

### Creating Arrays

In [2]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float)

print(f"a:\n{a}")
print(f"b:\n{b}")
print(f"c:\n{c}")

a:
[1 2 3]
b:
[[1.5 2.  3. ]
 [4.  5.  6. ]]
c:
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [3]:
print(f"zeros:\n{np.zeros((3,4))}") #Create an array of zeros
print(f"ones:\n{np.ones((2,3,4),dtype=np.int16)}") #Create an array of ones
print(f"arange:\n{ np.arange(10,25,5)}") #Create an array of evenly spaced values (step value)
print(f"linspace:\n{np.linspace(0,2,9)}") #Create an array of evenlyspaced values (number of samples)
print(f"full:\n{np.full((2,2),7)}") #Create a constant array
print(f"eye:\n{np.eye(2)}") #Create a 2X2 identity matrix
print(f"random:\n{np.random.random((2,2))}") #Create an array with random values
print(f"empty:\n{np.empty((3,2))}") #Create an empty array

zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones:
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
arange:
[10 15 20]
linspace:
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
full:
[[7 7]
 [7 7]]
eye:
[[1. 0.]
 [0. 1.]]
random:
[[0.99947062 0.36766825]
 [0.64068206 0.56773307]]
empty:
[[1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]]


### I/O

In [4]:
a = np.random.random((2,2))
b = np.random.random((2,2))
print(f"a:\n{a}")
print(f"a:\n{b}")
np.save('my_array' , a)
print(f"loading a:\n{np.load('my_array.npy')}")

a:
[[0.89544607 0.25142219]
 [0.07646361 0.64283289]]
a:
[[0.31699701 0.41379326]
 [0.16368251 0.86271526]]
loading a:
[[0.89544607 0.25142219]
 [0.07646361 0.64283289]]


[numpy.savez](https://numpy.org/doc/stable/reference/generated/numpy.savez.html)

In [5]:
np.savez('array.npz', a=a, b=b)
npzfile = np.load('array.npz')
print(f"npzfile['a']:\n{npzfile['a']}")
print(f"npzfile['b']:\n{npzfile['b']}")

npzfile['a']:
[[0.89544607 0.25142219]
 [0.07646361 0.64283289]]
npzfile['b']:
[[0.31699701 0.41379326]
 [0.16368251 0.86271526]]


In [6]:
np.savetxt('myfile.txt', a)
print(np.loadtxt('myfile.txt'))


[[0.89544607 0.25142219]
 [0.07646361 0.64283289]]


In [7]:
np.savetxt( 'my_file.csv', a, delimiter=',')
print(np.genfromtxt('my_file.csv', delimiter=','))

[[0.89544607 0.25142219]
 [0.07646361 0.64283289]]


### Asking For Help

In [8]:
print(np.info(np.ndarray.dtype))

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>
None


### Inspecting Your Array

In [9]:
print(f"shape: {a.shape}") #Array dimensions
print(f"len: {len(a)}")#Length of array
print(f"ndim: {a.ndim}") #Number of array dimensions
print(f"size: {a.size}") #Number of array elements
print(f"dtype:{a.dtype}")  #Data type of array elements
print(f"dtype.name: {a.dtype.name}")  #Name of data type
print(f"astype:\n{a.astype(int)}") #Convert an array to a different type

shape: (2, 2)
len: 2
ndim: 2
size: 4
dtype:float64
dtype.name: float64
astype:
[[0 0]
 [0 0]]


### Data Types

In [10]:
c = np.array([3.1415, 2.718, -1, 0])
print(f"original: {c}")
print(f"int_: {c.astype(np.int_)}") #Signed integer
print(f"uint: {c.astype(np.uint)}") #Unsigned integer
print(f"float_: {c.astype(np.float_)}") #Floating point
print(f"complex_: {c.astype(np.complex_)}") #Complex numbers
print(f"bool_: {c.astype(np.bool_)}")  #Boolean type storing TRUE and FALSE values
print(f"object_: {c.astype(np.object_)}") #Python object type
print(f"string_: {c.astype(np.string_)}") #Fixed-length string type
print(f"unicode_: {c.astype(np.unicode_)}") #Fixed-length unicode type

original: [ 3.1415  2.718  -1.      0.    ]
int_: [ 3  2 -1  0]
uint: [         3          2 4294967295          0]
float_: [ 3.1415  2.718  -1.      0.    ]
complex_: [ 3.1415+0.j  2.718 +0.j -1.    +0.j  0.    +0.j]
bool_: [ True  True  True False]
object_: [3.1415 2.718 -1.0 0.0]
string_: [b'3.1415' b'2.718' b'-1.0' b'0.0']
unicode_: ['3.1415' '2.718' '-1.0' '0.0']


### Array Mathematics
#### Subtraction

In [11]:
print(f"a-b:\n{a-b}")
print(f"np.subtract(a,b):\n{np.subtract(a, b)}")

a-b:
[[ 0.57844907 -0.16237107]
 [-0.0872189  -0.21988238]]
np.subtract(a,b):
[[ 0.57844907 -0.16237107]
 [-0.0872189  -0.21988238]]


#### Addition

In [12]:
print(f"a+b:\n{a+b}")
print(f"np.add(a,b):\n{np.add(a, b)}")

a+b:
[[1.21244308 0.66521545]
 [0.24014613 1.50554815]]
np.add(a,b):
[[1.21244308 0.66521545]
 [0.24014613 1.50554815]]


#### Multiplication (element-wise)

In [13]:
print(f"a*b:\n{a*b}")
print(f"np.multiply(a,b):\n{np.multiply(a, b)}")

a*b:
[[0.28385372 0.10403681]
 [0.01251576 0.55458174]]
np.multiply(a,b):
[[0.28385372 0.10403681]
 [0.01251576 0.55458174]]


### Division (element-wise)

In [14]:
print(f"a/b:\n{a/b}")
print(f"np.divide(a,b):\n{np.divide(a, b)}")

a/b:
[[2.8247777  0.60760339]
 [0.4671459  0.74512752]]
np.divide(a,b):
[[2.8247777  0.60760339]
 [0.4671459  0.74512752]]


#### Exponentiation (e^x)

In [15]:
print(f"a:\n{a}")
print(f"np.exp(a):\n{np.exp(a)}")
import math
print(f"math.e**a:\n{math.e**a}")

a:
[[0.89544607 0.25142219]
 [0.07646361 0.64283289]]
np.exp(a):
[[2.44842772 1.28585284]
 [1.07946291 1.90186101]]
math.e**a:
[[2.44842772 1.28585284]
 [1.07946291 1.90186101]]


#### Square root

In [16]:
print(f"a:\n{a}")
print(f"np.sqrt(a):\n{np.sqrt(a)}")
print(f"a**(0.5):\n{a**(0.5)}")

a:
[[0.89544607 0.25142219]
 [0.07646361 0.64283289]]
np.sqrt(a):
[[0.94628012 0.50142017]
 [0.27652055 0.8017686 ]]
a**(0.5):
[[0.94628012 0.50142017]
 [0.27652055 0.8017686 ]]


#### Sine (radians)

In [18]:
print(f"a:\n{a}")
print(f"np.sin(a):\n{np.sin(a)}")
#print(f"math.sin(a):\n{math.sin(a)}") does notwork

a:
[[0.89544607 0.25142219]
 [0.07646361 0.64283289]]
np.sin(a):
[[0.78048803 0.24878168]
 [0.07638913 0.59946529]]
