# Homework 2
## Mengxiang Jiang

The majority of the code here comes from the [NumPy Cheat Sheet](https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python)
and the [Pandas Basics Cheat Sheet](https://www.datacamp.com/cheat-sheet/pandas-cheat-sheet-for-data-science-in-python). 
If the code comes from somewhere else it will have a source linked to the original. Some of the code has been modified from the original to show errors or to remove errors.\
[Video Link](https://youtu.be/ZBcMe8eCq24)

### Importing Numpy

In [1]:
import numpy as np

### Creating Arrays

In [2]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float)

print(f"a:\n{a}")
print(f"b:\n{b}")
print(f"c:\n{c}")

a:
[1 2 3]
b:
[[1.5 2.  3. ]
 [4.  5.  6. ]]
c:
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [3]:
print(f"zeros:\n{np.zeros((3,4))}") #Create an array of zeros
print(f"ones:\n{np.ones((2,3,4),dtype=np.int16)}") #Create an array of ones
print(f"arange:\n{ np.arange(10,25,5)}") #Create an array of evenly spaced values (step value)
print(f"linspace:\n{np.linspace(0,2,9)}") #Create an array of evenlyspaced values (number of samples)
print(f"full:\n{np.full((2,2),7)}") #Create a constant array
print(f"eye:\n{np.eye(2)}") #Create a 2X2 identity matrix
print(f"random:\n{np.random.random((2,2))}") #Create an array with random values
print(f"empty:\n{np.empty((3,2))}") #Create an empty array

zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones:
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
arange:
[10 15 20]
linspace:
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
full:
[[7 7]
 [7 7]]
eye:
[[1. 0.]
 [0. 1.]]
random:
[[0.50884302 0.18780538]
 [0.27177352 0.41762909]]
empty:
[[1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]]


### I/O

In [4]:
a = np.random.random((2,2))
b = np.random.random((2,2))
print(f"a:\n{a}")
print(f"a:\n{b}")
np.save('my_array' , a)
print(f"loading a:\n{np.load('my_array.npy')}")

a:
[[0.64983541 0.65581982]
 [0.85967918 0.67902368]]
a:
[[0.15152542 0.3715619 ]
 [0.88429955 0.95671499]]
loading a:
[[0.64983541 0.65581982]
 [0.85967918 0.67902368]]


[numpy.savez](https://numpy.org/doc/stable/reference/generated/numpy.savez.html)

In [5]:
np.savez('array.npz', a=a, b=b)
npzfile = np.load('array.npz')
print(f"npzfile['a']:\n{npzfile['a']}")
print(f"npzfile['b']:\n{npzfile['b']}")

npzfile['a']:
[[0.64983541 0.65581982]
 [0.85967918 0.67902368]]
npzfile['b']:
[[0.15152542 0.3715619 ]
 [0.88429955 0.95671499]]


In [6]:
np.savetxt('myfile.txt', a)
print(np.loadtxt('myfile.txt'))


[[0.64983541 0.65581982]
 [0.85967918 0.67902368]]


In [7]:
np.savetxt( 'my_file.csv', a, delimiter=',')
print(np.genfromtxt('my_file.csv', delimiter=','))

[[0.64983541 0.65581982]
 [0.85967918 0.67902368]]


### Asking For Help

In [8]:
print(np.info(np.ndarray.dtype))

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>
None


### Inspecting Your Array

In [9]:
print(f"shape: {a.shape}") #Array dimensions
print(f"len: {len(a)}")#Length of array
print(f"ndim: {a.ndim}") #Number of array dimensions
print(f"size: {a.size}") #Number of array elements
print(f"dtype:{a.dtype}")  #Data type of array elements
print(f"dtype.name: {a.dtype.name}")  #Name of data type
print(f"astype:\n{a.astype(int)}") #Convert an array to a different type

shape: (2, 2)
len: 2
ndim: 2
size: 4
dtype:float64
dtype.name: float64
astype:
[[0 0]
 [0 0]]


### Data Types

In [10]:
c = np.array([3.1415, 2.718, -1, 0])
print(f"original: {c}")
print(f"int_: {c.astype(np.int_)}") #Signed integer
print(f"uint: {c.astype(np.uint)}") #Unsigned integer
print(f"float_: {c.astype(np.float_)}") #Floating point
print(f"complex_: {c.astype(np.complex_)}") #Complex numbers
print(f"bool_: {c.astype(np.bool_)}")  #Boolean type storing TRUE and FALSE values
print(f"object_: {c.astype(np.object_)}") #Python object type
print(f"string_: {c.astype(np.string_)}") #Fixed-length string type
print(f"unicode_: {c.astype(np.unicode_)}") #Fixed-length unicode type

original: [ 3.1415  2.718  -1.      0.    ]
int_: [ 3  2 -1  0]
uint: [         3          2 4294967295          0]
float_: [ 3.1415  2.718  -1.      0.    ]
complex_: [ 3.1415+0.j  2.718 +0.j -1.    +0.j  0.    +0.j]
bool_: [ True  True  True False]
object_: [3.1415 2.718 -1.0 0.0]
string_: [b'3.1415' b'2.718' b'-1.0' b'0.0']
unicode_: ['3.1415' '2.718' '-1.0' '0.0']


### Array Mathematics
#### Subtraction

In [11]:
print(f"a-b:\n{a-b}")
print(f"np.subtract(a,b):\n{np.subtract(a, b)}")

a-b:
[[ 0.49830999  0.28425792]
 [-0.02462037 -0.27769131]]
np.subtract(a,b):
[[ 0.49830999  0.28425792]
 [-0.02462037 -0.27769131]]


#### Addition

In [12]:
print(f"a+b:\n{a+b}")
print(f"np.add(a,b):\n{np.add(a, b)}")

a+b:
[[0.80136083 1.02738172]
 [1.74397873 1.63573867]]
np.add(a,b):
[[0.80136083 1.02738172]
 [1.74397873 1.63573867]]


#### Multiplication (element-wise)

In [13]:
print(f"a*b:\n{a*b}")
print(f"np.multiply(a,b):\n{np.multiply(a, b)}")

a*b:
[[0.09846658 0.24367766]
 [0.76021391 0.64963213]]
np.multiply(a,b):
[[0.09846658 0.24367766]
 [0.76021391 0.64963213]]


### Division (element-wise)

In [14]:
print(f"a/b:\n{a/b}")
print(f"np.divide(a,b):\n{np.divide(a, b)}")

a/b:
[[4.28862309 1.76503516]
 [0.97215833 0.709745  ]]
np.divide(a,b):
[[4.28862309 1.76503516]
 [0.97215833 0.709745  ]]


#### Exponentiation (e^x)

In [15]:
print(f"a:\n{a}")
print(f"np.exp(a):\n{np.exp(a)}")
import math
print(f"math.e**a:\n{math.e**a}")

a:
[[0.64983541 0.65581982]
 [0.85967918 0.67902368]]
np.exp(a):
[[1.91522557 1.92672143]
 [2.36240266 1.97195153]]
math.e**a:
[[1.91522557 1.92672143]
 [2.36240266 1.97195153]]


#### Square root

In [16]:
print(f"a:\n{a}")
print(f"np.sqrt(a):\n{np.sqrt(a)}")
print(f"a**(0.5):\n{a**(0.5)}")

a:
[[0.64983541 0.65581982]
 [0.85967918 0.67902368]]
np.sqrt(a):
[[0.80612369 0.80982703]
 [0.92718886 0.82402893]]
a**(0.5):
[[0.80612369 0.80982703]
 [0.92718886 0.82402893]]


#### Sine (radians)

In [62]:
print(f"a:\n{a}")
print(f"np.sin(a):\n{np.sin(a)}")
#print(f"math.sin(a):\n{math.sin(a)}") does not work
vec_sin = np.vectorize(math.sin)
print(f"vec_sin(a):\n{vec_sin(a)}")

a:
[[0.62323626 0.31479988 0.21953848 0.79783131 0.48802276 0.63590151]
 [0.88169528 0.64061188 0.88039052 0.13475182 0.47543171 0.62420983]]
np.sin(a):
[[0.58366604 0.30962619 0.21777921 0.71584347 0.46888039 0.59390305]
 [0.77181792 0.59768611 0.77098764 0.13434438 0.45772232 0.58445629]]
vec_sin(a):
[[0.58366604 0.30962619 0.21777921 0.71584347 0.46888039 0.59390305]
 [0.77181792 0.59768611 0.77098764 0.13434438 0.45772232 0.58445629]]


#### Cosine

In [18]:
print(f"a:\n{a}")
print(f"np.cos(a):\n{np.cos(a)}")

a:
[[0.64983541 0.65581982]
 [0.85967918 0.67902368]]
np.cos(a):
[[0.7961834  0.79254826]
 [0.65268057 0.77818625]]


#### Natural Log

In [19]:
print(f"a:\n{a}")
print(f"np.log(a):\n{np.log(a)}")

a:
[[0.64983541 0.65581982]
 [0.85967918 0.67902368]]
np.log(a):
[[-0.43103617 -0.4218692 ]
 [-0.15119601 -0.38709928]]


#### Dot Product

In [20]:
print(f"a:\n{a}")
print(f"b:\n{b}")
print(f"a.dot(b):\n{a.dot(b)}")

a:
[[0.64983541 0.65581982]
 [0.85967918 0.67902368]]
b:
[[0.15152542 0.3715619 ]
 [0.88429955 0.95671499]]
a.dot(b):
[[0.67840775 0.86888673]
 [0.73072358 0.96905616]]


#### Comparison

In [21]:
print(f"a == a:\n{a == a}")
print(f"a == b:\n{a == b}")
print(f"a < 0.5 :\n{a < 0.5}")
print(f"np.array_equal(a, a):\n{np.array_equal(a, a)}")
print(f"np.array_equal(a, b):\n{np.array_equal(a, b)}")

a == a:
[[ True  True]
 [ True  True]]
a == b:
[[False False]
 [False False]]
a < 0.5 :
[[False False]
 [False False]]
np.array_equal(a, a):
True
np.array_equal(a, b):
False


### Copying Arrays 

In [22]:
a = np.random.random((2,2))
h = a.view() #Create a view of the array with the same data
print(f"a:\n{a}")
print(f"h:\n{h}")
h[0][0] = 0
print("After modifying h[0][0] = 0")
print(f"a:\n{a}")
print(f"h:\n{h}")

a:
[[0.40338479 0.77303925]
 [0.1982853  0.35014665]]
h:
[[0.40338479 0.77303925]
 [0.1982853  0.35014665]]
After modifying h[0][0] = 0
a:
[[0.         0.77303925]
 [0.1982853  0.35014665]]
h:
[[0.         0.77303925]
 [0.1982853  0.35014665]]


In [23]:
a = np.random.random((2,2))
h = np.copy(a) #Create a copy of the array
print(f"a:\n{a}")
print(f"h:\n{h}")
h[0][0] = 0
print("After modifying h[0][0] = 0")
print(f"a:\n{a}")
print(f"h:\n{h}")

class Dog():
    def __init__(self, name):
        self.name = name
print("testing objects:")
a = np.array([Dog('foo')])
h = np.copy(a) #Create a copy of the array
print(f"a:\n{a}")
print(f"h:\n{h}")
h[0].name = 'bar'
print("After modifying h[0].name = 'bar'")
print(f"a[0].name:\n{a[0].name}")
print(f"h[0].name:\n{h[0].name}")

a:
[[0.79844512 0.12503969]
 [0.37729892 0.40272517]]
h:
[[0.79844512 0.12503969]
 [0.37729892 0.40272517]]
After modifying h[0][0] = 0
a:
[[0.79844512 0.12503969]
 [0.37729892 0.40272517]]
h:
[[0.         0.12503969]
 [0.37729892 0.40272517]]
testing objects:
a:
h:
After modifying h[0].name = 'bar'
a[0].name:
bar
h[0].name:
bar


In [24]:
a = np.random.random((2,2))
h = a.copy() #Create a "deep" copy of the array
print(f"a:\n{a}")
print(f"h:\n{h}")
h[0][0] = 0
print("After modifying h[0][0] = 0")
print(f"a:\n{a}")
print(f"h:\n{h}")
print("testing objects:")
a = np.array([Dog('foo')])
h = a.copy() #Create a "deep" copy of the array
print(f"a:\n{a}")
print(f"h:\n{h}")
h[0].name = 'bar'
print("After modifying h[0].name = 'bar'")
print(f"a[0].name:\n{a[0].name}")
print(f"h[0].name:\n{h[0].name}")

a:
[[0.21412216 0.72402426]
 [0.07359884 0.61690243]]
h:
[[0.21412216 0.72402426]
 [0.07359884 0.61690243]]
After modifying h[0][0] = 0
a:
[[0.21412216 0.72402426]
 [0.07359884 0.61690243]]
h:
[[0.         0.72402426]
 [0.07359884 0.61690243]]
testing objects:
a:
h:
After modifying h[0].name = 'bar'
a[0].name:
bar
h[0].name:
bar


In [25]:
import copy
a = np.random.random((2,2))
h = copy.deepcopy(a) #Create a real deep copy of the array
print(f"a:\n{a}")
print(f"h:\n{h}")
h[0][0] = 0
print("After modifying h[0][0] = 0")
print(f"a:\n{a}")
print(f"h:\n{h}")
print("testing objects:")
a = np.array([Dog('foo')])
h = copy.deepcopy(a) #Create a real deep copy of the array
print(f"a:\n{a}")
print(f"h:\n{h}")
h[0].name = 'bar'
print("After modifying h[0].name = 'bar'")
print(f"a[0].name:\n{a[0].name}")
print(f"h[0].name:\n{h[0].name}")

a:
[[0.99560486 0.35168596]
 [0.92713033 0.37862869]]
h:
[[0.99560486 0.35168596]
 [0.92713033 0.37862869]]
After modifying h[0][0] = 0
a:
[[0.99560486 0.35168596]
 [0.92713033 0.37862869]]
h:
[[0.         0.35168596]
 [0.92713033 0.37862869]]
testing objects:
a:
h:
After modifying h[0].name = 'bar'
a[0].name:
foo
h[0].name:
bar


### Sorting Arrays 

In [26]:
a = np.random.random((2,2,2))
print(f"a:\n{a}")
a.sort()
print(f"a after a.sort():\n{a}")
b = np.random.random((2,2,2))
print(f"b:\n{b}")
b.sort(axis=0)
print(f"b after b.sort(axis=0):\n{b}")
c = np.random.random((2,2,2))
print(f"c:\n{c}")
c.sort(axis=1)
print(f"c after c.sort(axis=1):\n{c}")
d = np.random.random((2,2,2))
print(f"d:\n{d}")
d.sort(axis=2)
print(f"d after d.sort(axis=2):\n{d}")

a:
[[[0.83067787 0.6557039 ]
  [0.19603069 0.98789956]]

 [[0.65200364 0.11165853]
  [0.75831615 0.05440025]]]
a after a.sort():
[[[0.6557039  0.83067787]
  [0.19603069 0.98789956]]

 [[0.11165853 0.65200364]
  [0.05440025 0.75831615]]]
b:
[[[0.78551522 0.57484006]
  [0.13161437 0.29985178]]

 [[0.68687138 0.30558548]
  [0.83670692 0.85900193]]]
b after b.sort(axis=0):
[[[0.68687138 0.30558548]
  [0.13161437 0.29985178]]

 [[0.78551522 0.57484006]
  [0.83670692 0.85900193]]]
c:
[[[0.25457727 0.48538013]
  [0.30360881 0.87961164]]

 [[0.89328544 0.21944112]
  [0.29232363 0.13413384]]]
c after c.sort(axis=1):
[[[0.25457727 0.48538013]
  [0.30360881 0.87961164]]

 [[0.29232363 0.13413384]
  [0.89328544 0.21944112]]]
d:
[[[0.39747589 0.86236098]
  [0.86831777 0.07061531]]

 [[0.05929095 0.41799079]
  [0.06456415 0.95734189]]]
d after d.sort(axis=2):
[[[0.39747589 0.86236098]
  [0.07061531 0.86831777]]

 [[0.05929095 0.41799079]
  [0.06456415 0.95734189]]]


### Subsetting, Slicing, Indexing

#### Subsetting

In [27]:
print(f"a:\n{a}")
print(f"a[1]:\n{a[1]}")
print(f"a[1][0]:\n{a[1][0]}")
print(f"a[1][0][1]:\n{a[1][0][1]}")

a:
[[[0.6557039  0.83067787]
  [0.19603069 0.98789956]]

 [[0.11165853 0.65200364]
  [0.05440025 0.75831615]]]
a[1]:
[[0.11165853 0.65200364]
 [0.05440025 0.75831615]]
a[1][0]:
[0.11165853 0.65200364]
a[1][0][1]:
0.6520036449019777


#### Slicing

In [28]:
a = np.random.random((3,3,3))
print(f"a:\n{a}")
print(f"a[0:2]:\n{a[0:2]}")
print(f"a[0:2, 1]:\n{a[0:2, 1]}")
print(f"a[0:2, 0:2]:\n{a[0:2, 0:2]}")
print(f"a[1, ...]:\n{a[1, ...]}")
print(f"a[::-1]:\n{a[::-1]}")

a:
[[[0.62323626 0.31479988 0.21953848]
  [0.79783131 0.48802276 0.63590151]
  [0.88169528 0.64061188 0.88039052]]

 [[0.13475182 0.47543171 0.62420983]
  [0.97402485 0.9613656  0.11136016]
  [0.49482418 0.07317145 0.59567927]]

 [[0.80932736 0.7748779  0.55991217]
  [0.98722024 0.42218809 0.36674666]
  [0.45342186 0.58563428 0.12383768]]]
a[0:2]:
[[[0.62323626 0.31479988 0.21953848]
  [0.79783131 0.48802276 0.63590151]
  [0.88169528 0.64061188 0.88039052]]

 [[0.13475182 0.47543171 0.62420983]
  [0.97402485 0.9613656  0.11136016]
  [0.49482418 0.07317145 0.59567927]]]
a[0:2, 1]:
[[0.79783131 0.48802276 0.63590151]
 [0.97402485 0.9613656  0.11136016]]
a[0:2, 0:2]:
[[[0.62323626 0.31479988 0.21953848]
  [0.79783131 0.48802276 0.63590151]]

 [[0.13475182 0.47543171 0.62420983]
  [0.97402485 0.9613656  0.11136016]]]
a[1, ...]:
[[0.13475182 0.47543171 0.62420983]
 [0.97402485 0.9613656  0.11136016]
 [0.49482418 0.07317145 0.59567927]]
a[::-1]:
[[[0.80932736 0.7748779  0.55991217]
  [0.9872

#### Boolean Indexing

In [29]:
print(f"a:\n{a}")
print(f"a[a<0.5]:\n{a[a<0.5]}")

a:
[[[0.62323626 0.31479988 0.21953848]
  [0.79783131 0.48802276 0.63590151]
  [0.88169528 0.64061188 0.88039052]]

 [[0.13475182 0.47543171 0.62420983]
  [0.97402485 0.9613656  0.11136016]
  [0.49482418 0.07317145 0.59567927]]

 [[0.80932736 0.7748779  0.55991217]
  [0.98722024 0.42218809 0.36674666]
  [0.45342186 0.58563428 0.12383768]]]
a[a<0.5]:
[0.31479988 0.21953848 0.48802276 0.13475182 0.47543171 0.11136016
 0.49482418 0.07317145 0.42218809 0.36674666 0.45342186 0.12383768]


#### Fancy Indexing

In [30]:
print(f"a:\n{a}")
print(f"a[[1,0,1,0],[0,1,2,0]]:\n{a[[1,0,1,0],[0,1,2,0]]}")
print(f"a[[1,0,1,0]][:,[0,1,2,0]]:\n{a[[1,0,1,0]][:,[0,1,2,0]]}")

a:
[[[0.62323626 0.31479988 0.21953848]
  [0.79783131 0.48802276 0.63590151]
  [0.88169528 0.64061188 0.88039052]]

 [[0.13475182 0.47543171 0.62420983]
  [0.97402485 0.9613656  0.11136016]
  [0.49482418 0.07317145 0.59567927]]

 [[0.80932736 0.7748779  0.55991217]
  [0.98722024 0.42218809 0.36674666]
  [0.45342186 0.58563428 0.12383768]]]
a[[1,0,1,0],[0,1,2,0]]:
[[0.13475182 0.47543171 0.62420983]
 [0.79783131 0.48802276 0.63590151]
 [0.49482418 0.07317145 0.59567927]
 [0.62323626 0.31479988 0.21953848]]
a[[1,0,1,0]][:,[0,1,2,0]]:
[[[0.13475182 0.47543171 0.62420983]
  [0.97402485 0.9613656  0.11136016]
  [0.49482418 0.07317145 0.59567927]
  [0.13475182 0.47543171 0.62420983]]

 [[0.62323626 0.31479988 0.21953848]
  [0.79783131 0.48802276 0.63590151]
  [0.88169528 0.64061188 0.88039052]
  [0.62323626 0.31479988 0.21953848]]

 [[0.13475182 0.47543171 0.62420983]
  [0.97402485 0.9613656  0.11136016]
  [0.49482418 0.07317145 0.59567927]
  [0.13475182 0.47543171 0.62420983]]

 [[0.6232362

### Array Manipulation 
#### Transposing Array

In [31]:
print(f"a:\n{a}")
print(f"np.transpose(a):\n{np.transpose(a)}")
print(f"a.T:\n{a.T}")

a:
[[[0.62323626 0.31479988 0.21953848]
  [0.79783131 0.48802276 0.63590151]
  [0.88169528 0.64061188 0.88039052]]

 [[0.13475182 0.47543171 0.62420983]
  [0.97402485 0.9613656  0.11136016]
  [0.49482418 0.07317145 0.59567927]]

 [[0.80932736 0.7748779  0.55991217]
  [0.98722024 0.42218809 0.36674666]
  [0.45342186 0.58563428 0.12383768]]]
np.transpose(a):
[[[0.62323626 0.13475182 0.80932736]
  [0.79783131 0.97402485 0.98722024]
  [0.88169528 0.49482418 0.45342186]]

 [[0.31479988 0.47543171 0.7748779 ]
  [0.48802276 0.9613656  0.42218809]
  [0.64061188 0.07317145 0.58563428]]

 [[0.21953848 0.62420983 0.55991217]
  [0.63590151 0.11136016 0.36674666]
  [0.88039052 0.59567927 0.12383768]]]
a.T:
[[[0.62323626 0.13475182 0.80932736]
  [0.79783131 0.97402485 0.98722024]
  [0.88169528 0.49482418 0.45342186]]

 [[0.31479988 0.47543171 0.7748779 ]
  [0.48802276 0.9613656  0.42218809]
  [0.64061188 0.07317145 0.58563428]]

 [[0.21953848 0.62420983 0.55991217]
  [0.63590151 0.11136016 0.3667466

#### Changing Array Shape

In [32]:
print(f"a:\n{a}")
print(f"a.ravel():\n{a.ravel()}")
print(f"a.reshape(3, -1):\n{a.reshape(3, -1)}")
print(f"a.reshape(-1, 3):\n{a.reshape(-1, 3)}")
print(f"a:\n{a}")

a:
[[[0.62323626 0.31479988 0.21953848]
  [0.79783131 0.48802276 0.63590151]
  [0.88169528 0.64061188 0.88039052]]

 [[0.13475182 0.47543171 0.62420983]
  [0.97402485 0.9613656  0.11136016]
  [0.49482418 0.07317145 0.59567927]]

 [[0.80932736 0.7748779  0.55991217]
  [0.98722024 0.42218809 0.36674666]
  [0.45342186 0.58563428 0.12383768]]]
a.ravel():
[0.62323626 0.31479988 0.21953848 0.79783131 0.48802276 0.63590151
 0.88169528 0.64061188 0.88039052 0.13475182 0.47543171 0.62420983
 0.97402485 0.9613656  0.11136016 0.49482418 0.07317145 0.59567927
 0.80932736 0.7748779  0.55991217 0.98722024 0.42218809 0.36674666
 0.45342186 0.58563428 0.12383768]
a.reshape(3, -1):
[[0.62323626 0.31479988 0.21953848 0.79783131 0.48802276 0.63590151
  0.88169528 0.64061188 0.88039052]
 [0.13475182 0.47543171 0.62420983 0.97402485 0.9613656  0.11136016
  0.49482418 0.07317145 0.59567927]
 [0.80932736 0.7748779  0.55991217 0.98722024 0.42218809 0.36674666
  0.45342186 0.58563428 0.12383768]]
a.reshape(-1,

#### Adding/Removing Elements 

In [33]:
a.resize((2,6)) # Does not return anything, rather modifies a into a 2x6 array if it has enough elements
print(f"a after a.resize((2,6)):\n{a}")
print(f"b:\n{b}")
print(f"c:\n{c}")
print(f"np.append(b, c):\n{np.append(b, c)}") # Returns 1D array with all elements of b followed by c
print(f"np.insert(a, 1, 5):\n{np.insert(a, 1, 5)}") # Returns 1D array with all elements of a with 5 inserted into index 1
print(f"np.delete(a, [1]):\n{np.delete(a, [1])}") # Returns 1D array with all elements of a with the element in index 1 removed
print(f"a:\n{a}")

a after a.resize((2,6)):
[[0.62323626 0.31479988 0.21953848 0.79783131 0.48802276 0.63590151]
 [0.88169528 0.64061188 0.88039052 0.13475182 0.47543171 0.62420983]]
b:
[[[0.68687138 0.30558548]
  [0.13161437 0.29985178]]

 [[0.78551522 0.57484006]
  [0.83670692 0.85900193]]]
c:
[[[0.25457727 0.48538013]
  [0.30360881 0.87961164]]

 [[0.29232363 0.13413384]
  [0.89328544 0.21944112]]]
np.append(b, c):
[0.68687138 0.30558548 0.13161437 0.29985178 0.78551522 0.57484006
 0.83670692 0.85900193 0.25457727 0.48538013 0.30360881 0.87961164
 0.29232363 0.13413384 0.89328544 0.21944112]
np.insert(a, 1, 5):
[0.62323626 5.         0.31479988 0.21953848 0.79783131 0.48802276
 0.63590151 0.88169528 0.64061188 0.88039052 0.13475182 0.47543171
 0.62420983]
np.delete(a, [1]):
[0.62323626 0.21953848 0.79783131 0.48802276 0.63590151 0.88169528
 0.64061188 0.88039052 0.13475182 0.47543171 0.62420983]
a:
[[0.62323626 0.31479988 0.21953848 0.79783131 0.48802276 0.63590151]
 [0.88169528 0.64061188 0.88039052 

#### Combining Arrays

In [34]:
print(f"b:\n{b}")
print(f"c:\n{c}")
print(f"np.concatenate((b, c),axis=0):\n{np.concatenate((b, c),axis=0)}") # if both b and c are NxMxO arrays, the result is an 2NxMxO array
print(f"np.concatenate((b, c),axis=1):\n{np.concatenate((b, c),axis=1)}") # if both b and c are NxMxO arrays, the result is an Nx2MxO array
print(f"np.concatenate((b, c),axis=2):\n{np.concatenate((b, c),axis=2)}") # if both b and c are NxMxO arrays, the result is an NxMx2O array
print(f"np.vstack((b, c)):\n{np.vstack((b, c))}") # same as np.concatenate((b, c),axis=0)
print(f"np.r_[b,c]:\n{np.r_[b,c]}") # same as np.concatenate((b, c),axis=0)
print(f"np.hstack((b, c)):\n{np.hstack((b, c))}") # same as np.concatenate((b, c),axis=1)
print(f"np.column_stack((b, c)):\n{np.column_stack((b, c))}") # same as np.concatenate((b, c),axis=1)
print(f"np.c_[b,c]:\n{np.c_[b,c]}") # same as np.concatenate((b, c),axis=2)

b:
[[[0.68687138 0.30558548]
  [0.13161437 0.29985178]]

 [[0.78551522 0.57484006]
  [0.83670692 0.85900193]]]
c:
[[[0.25457727 0.48538013]
  [0.30360881 0.87961164]]

 [[0.29232363 0.13413384]
  [0.89328544 0.21944112]]]
np.concatenate((b, c),axis=0):
[[[0.68687138 0.30558548]
  [0.13161437 0.29985178]]

 [[0.78551522 0.57484006]
  [0.83670692 0.85900193]]

 [[0.25457727 0.48538013]
  [0.30360881 0.87961164]]

 [[0.29232363 0.13413384]
  [0.89328544 0.21944112]]]
np.concatenate((b, c),axis=1):
[[[0.68687138 0.30558548]
  [0.13161437 0.29985178]
  [0.25457727 0.48538013]
  [0.30360881 0.87961164]]

 [[0.78551522 0.57484006]
  [0.83670692 0.85900193]
  [0.29232363 0.13413384]
  [0.89328544 0.21944112]]]
np.concatenate((b, c),axis=2):
[[[0.68687138 0.30558548 0.25457727 0.48538013]
  [0.13161437 0.29985178 0.30360881 0.87961164]]

 [[0.78551522 0.57484006 0.29232363 0.13413384]
  [0.83670692 0.85900193 0.89328544 0.21944112]]]
np.vstack((b, c)):
[[[0.68687138 0.30558548]
  [0.13161437 0.

#### Splitting Arrays

In [35]:
print(f"b:\n{a}")
print(f"np.vsplit(a,2):\n{np.vsplit(a,2)}") # since a is 2x6, this splits a into two 1x6 arrays
print(f"np.hsplit(a,3):\n{np.hsplit(a,3)}") # since a is 2x6, this splits a into three 2x2 arrays

b:
[[0.62323626 0.31479988 0.21953848 0.79783131 0.48802276 0.63590151]
 [0.88169528 0.64061188 0.88039052 0.13475182 0.47543171 0.62420983]]
np.vsplit(a,2):
[array([[0.62323626, 0.31479988, 0.21953848, 0.79783131, 0.48802276,
        0.63590151]]), array([[0.88169528, 0.64061188, 0.88039052, 0.13475182, 0.47543171,
        0.62420983]])]
np.hsplit(a,3):
[array([[0.62323626, 0.31479988],
       [0.88169528, 0.64061188]]), array([[0.21953848, 0.79783131],
       [0.88039052, 0.13475182]]), array([[0.48802276, 0.63590151],
       [0.47543171, 0.62420983]])]


### Importing Pandas

In [36]:
import pandas as pd

### Pandas Data Structures
#### Series

In [37]:
s = pd.Series([3, -5, 7, 4], index=['a', 'b', 'c', 'd'])
print(s)

a    3
b   -5
c    7
d    4
dtype: int64


#### DataFrame

In [38]:
data = {
    'Country': ['Belgium', 'India', 'Brazil'],
    'Capital': ['Brussels', 'New Delhi', 'Brasilia'],
    'Population': [11190846, 1303171035, 207847528]
}

df = pd.DataFrame(data, columns=['Country', 'Capital', 'Population'])
print(df)

   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528


#### Asking For Help

In [39]:
help(pd.Series.loc)

Help on property:

    Access a group of rows and columns by label(s) or a boolean array.
    
    ``.loc[]`` is primarily label based, but may also be used with a
    boolean array.
    
    Allowed inputs are:
    
    - A single label, e.g. ``5`` or ``'a'``, (note that ``5`` is
      interpreted as a *label* of the index, and **never** as an
      integer position along the index).
    - A list or array of labels, e.g. ``['a', 'b', 'c']``.
    - A slice object with labels, e.g. ``'a':'f'``.
    
      .. warning:: Note that contrary to usual python slices, **both** the
          start and the stop are included
    
    - A boolean array of the same length as the axis being sliced,
      e.g. ``[True, False, True]``.
    - An alignable boolean Series. The index of the key will be aligned before
      masking.
    - An alignable Index. The Index of the returned selection will be the input.
    - A ``callable`` function with one argument (the calling Series or
      DataFrame) and that

### I/O
#### Read and Write to CSV
[How to get rid of "Unamed: 0" column in a pandas DataFrame read in from CSV file](https://stackoverflow.com/questions/36519086/how-to-get-rid-of-unnamed-0-column-in-a-pandas-dataframe-read-in-from-csv-fil)

In [40]:
print(f"df:\n{df}")
df.to_csv('myDataFrame.csv')
df2 = pd.read_csv('myDataFrame.csv')
print(f"df2:\n{df2}")
df3 = pd.read_csv('myDataFrame.csv', index_col=[0])
print(f"df3:\n{df3}")

df:
   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528
df2:
   Unnamed: 0  Country    Capital  Population
0           0  Belgium   Brussels    11190846
1           1    India  New Delhi  1303171035
2           2   Brazil   Brasilia   207847528
df3:
   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528


#### Read and Write to Excel
[ModuleNotFoundError: No module named 'openpyxl'](https://pythonexamples.org/modulenotfounderror-no-module-named-openpyxl/)

In [41]:
print(f"df:\n{df}")
df.to_excel('myDataFrame.xlsx')
df2 = pd.read_excel('myDataFrame.xlsx')
print(f"df2:\n{df2}")
df3 = pd.read_excel('myDataFrame.xlsx', index_col=[0])
print(f"df3:\n{df3}")

df:
   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528
df2:
   Unnamed: 0  Country    Capital  Population
0           0  Belgium   Brussels    11190846
1           1    India  New Delhi  1303171035
2           2   Brazil   Brasilia   207847528
df3:
   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528


### Selection
#### Getting

In [42]:
print(f"s:\n{s}")
print(f"s['b']:\n{s['b']}")

s:
a    3
b   -5
c    7
d    4
dtype: int64
s['b']:
-5


In [43]:
print(f"df:\n{df}")
print(f"df[1:]:\n{df[1:]}")

df:
   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528
df[1:]:
  Country    Capital  Population
1   India  New Delhi  1303171035
2  Brazil   Brasilia   207847528


#### Selecting
##### By Position

In [44]:
print(f"df:\n{df}")
print(f"df.iloc[0:1, :]:\n{df.iloc[0:1, 0:1]}") # for a single value or slice
print(f"df.iat[0, 0]:\n{df.iat[0, 0]}") # for a single value

df:
   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528
df.iloc[0:1, :]:
   Country
0  Belgium
df.iat[0, 0]:
Belgium


##### By Label

In [45]:
print(f"df:\n{df}")
print(f"df.loc[0:1, 'Country']:\n{df.loc[0:1, ['Country', 'Capital']]}") # for a single value or slice
print(f"df.at[0, 'Country']:\n{df.at[0, 'Country']}") # for a single value

df:
   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528
df.loc[0:1, 'Country']:
   Country    Capital
0  Belgium   Brussels
1    India  New Delhi
df.at[0, 'Country']:
Belgium


##### By Label/Position
[AttributeError: 'DataFrame' object has no attribute 'ix'](https://stackoverflow.com/questions/59991397/attributeerror-dataframe-object-has-no-attribute-ix)

In [46]:
# print(f"df:\n{df}")
# print(f"df.ix[2]:\n{df.ix[2]}") ix has been deprecated as well as removed

##### Boolean Indexing

In [47]:
print(f"s:\n{s}")
print(f"s[~(s > 1)]:\n{s[~(s > 1)]}")

s:
a    3
b   -5
c    7
d    4
dtype: int64
s[~(s > 1)]:
b   -5
dtype: int64


In [48]:
print(f"s[(s < -1) | (s > 3)]:\n{s[(s < -1) | (s > 3)]}")

s[(s < -1) | (s > 3)]:
b   -5
c    7
d    4
dtype: int64


In [49]:
print(f"df:\n{df}")
print(f"df[df['Population'] > 200000000]:\n{df[df['Population'] > 200000000]}")

df:
   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528
df[df['Population'] > 200000000]:
  Country    Capital  Population
1   India  New Delhi  1303171035
2  Brazil   Brasilia   207847528


##### Setting

In [50]:
print(f"s:\n{s}")
s['a'] = 6
print(f"s after s['a'] = 6: \n{s}")

s:
a    3
b   -5
c    7
d    4
dtype: int64
s after s['a'] = 6: 
a    6
b   -5
c    7
d    4
dtype: int64


### Dropping

In [51]:
print(f"s:\n{s}")
print(f"s.drop(['a', 'c']): \n{s.drop(['a',  'c'])}") # Returns a series with specified labels removed

s:
a    6
b   -5
c    7
d    4
dtype: int64
s.drop(['a', 'c']): 
b   -5
d    4
dtype: int64


In [52]:
print(f"df:\n{df}")
print(f"df.drop('Country', axis=1): \n{df.drop('Country', axis=1)}") # Returns a dataframe with specified labels removed

df:
   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528
df.drop('Country', axis=1): 
     Capital  Population
0   Brussels    11190846
1  New Delhi  1303171035
2   Brasilia   207847528


### Sort and Rank

In [53]:
print(f"df:\n{df}")
print(f"df.sort_index(ascending=False):\n{df.sort_index(ascending=False)}") # Returns a new dataframe by default unless inplace is set to True
print(f"df:\n{df}")

df:
   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528
df.sort_index(ascending=False):
   Country    Capital  Population
2   Brazil   Brasilia   207847528
1    India  New Delhi  1303171035
0  Belgium   Brussels    11190846
df:
   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528


In [54]:
print(f"df:\n{df}")
print(f"df.sort_values(by='Country'):\n{df.sort_values(by='Country')}") # Returns a new dataframe by default unless inplace is set to True
print(f"df:\n{df}")

df:
   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528
df.sort_values(by='Country'):
   Country    Capital  Population
0  Belgium   Brussels    11190846
2   Brazil   Brasilia   207847528
1    India  New Delhi  1303171035
df:
   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528


In [55]:
print(f"df:\n{df}")
print(f"df.rank():\n{df.rank()}")

df:
   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528
df.rank():
   Country  Capital  Population
0      1.0      2.0         1.0
1      3.0      3.0         3.0
2      2.0      1.0         2.0


### Retrieving Series/DataFrame Information
#### Basic Information

In [56]:
print(f"df:\n{df}")
print(f"df.shape:\n{df.shape}")
print(f"df.index:\n{df.index}")
print(f"df.columns:\n{df.columns}")
print("df.info():")
df.info()
print(f"df.count():\n{df.count()}")

df:
   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528
df.shape:
(3, 3)
df.index:
RangeIndex(start=0, stop=3, step=1)
df.columns:
Index(['Country', 'Capital', 'Population'], dtype='object')
df.info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Country     3 non-null      object
 1   Capital     3 non-null      object
 2   Population  3 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 200.0+ bytes
df.count():
Country       3
Capital       3
Population    3
dtype: int64


#### Summary

In [57]:
print(f"df:\n{df}")
print(f"df.sum():\n{df.sum()}")
print(f"df.cumsum():\n{df.cumsum()}")
print(f"df.min():\n{df.min()}")
print(f"df.max():\n{df.max()}")
print(f"df['Population'].idxmin():\n{df['Population'].idxmin()}") # need to specify a numeric column
print(f"df['Population'].idxmax():\n{df['Population'].idxmax()}") # need to specify a numeric column
print(f"df.describe():\n{df.describe()}")
print(f"df['Population'].mean():\n{df['Population'].mean()}") # need to specify a numeric column
print(f"df['Population'].median():\n{df['Population'].median()}") # need to specify a numeric column

df:
   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528
df.sum():
Country              BelgiumIndiaBrazil
Capital       BrusselsNew DelhiBrasilia
Population                   1522209409
dtype: object
df.cumsum():
              Country                    Capital  Population
0             Belgium                   Brussels    11190846
1        BelgiumIndia          BrusselsNew Delhi  1314361881
2  BelgiumIndiaBrazil  BrusselsNew DelhiBrasilia  1522209409
df.min():
Country        Belgium
Capital       Brasilia
Population    11190846
dtype: object
df.max():
Country            India
Capital        New Delhi
Population    1303171035
dtype: object
df['Population'].idxmin():
0
df['Population'].idxmax():
1
df.describe():
         Population
count  3.000000e+00
mean   5.074031e+08
std    6.961346e+08
min    1.119085e+07
25%    1.095192e+08
50%    2.078475e+08
75%    7.555093e+08
max    1.303171e+09
df['Population

### Applying Functions
[pandas.DataFrame.apply](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html)\
[pandas.DataFrame.applymap](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.applymap.html)

In [58]:
f = np.sum
print(f"f:\n{f}")
print(f"df:\n{df}")
print(f"df.apply(f):\n{df.apply(f)}")
g = lambda x: x*2
print(f"g:\n{g}")
print(f"df.applymap(g):\n{df.applymap(g)}")

f:
<function sum at 0x000001C37FAE42C0>
df:
   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528
df.apply(f):
Country              BelgiumIndiaBrazil
Capital       BrusselsNew DelhiBrasilia
Population                   1522209409
dtype: object
g:
<function <lambda> at 0x000001C316476840>
df.applymap(g):
          Country             Capital  Population
0  BelgiumBelgium    BrusselsBrussels    22381692
1      IndiaIndia  New DelhiNew Delhi  2606342070
2    BrazilBrazil    BrasiliaBrasilia   415695056


### Internal Data Alignment

In [59]:
s3 = pd.Series([7, -2, 3],  index=['a', 'c', 'd'])
print(f"s:\n{s}")
print(f"s3:\n{s3}")
print(f"s + s3:\n{s + s3}")

s:
a    6
b   -5
c    7
d    4
dtype: int64
s3:
a    7
c   -2
d    3
dtype: int64
s + s3:
a    13.0
b     NaN
c     5.0
d     7.0
dtype: float64


### Arithmetic Operations with Fill Methods

In [60]:
print(f"s.add(s3, fill_value=0):\n{s.add(s3, fill_value=0)}")

s.add(s3, fill_value=0):
a    13.0
b    -5.0
c     5.0
d     7.0
dtype: float64
